[package]
name = "commeatus-dns"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Commeatus DNS engine and resolver failure domain"

[dependencies]
commeatus-transport = { path = "../transport", version = "=0.5.0-alpha.1" }
